### ISSUE TITLE
Entries missing in history yaml

### ISSUE THREAD

**Issue by FlorianTaube** [tillbiskup/cwepr#1]
Importing data via:

datasets:
  - source: File.txt
  - packge: aspecd
  - importer: TxtImporter
  
leads to a History.yaml that can no longer be served because the entries
  - packge: aspecd
  - importer: TxtImporter
are not included in it.

**Comment by tillbiskup** [comment]
Thanks for reporting. This was indeed an upstream bug in ASpecD that should have been fixed with release 0.8.1.
Please update your ASpecD package (via pip) and check. If the problem still persists, please do reopen the issue.
