### ISSUE TITLE
Multiplotter ERROR

### ISSUE THREAD

**Issue by FlorianTaube** [tillbiskup/cwepr#2]
If you do not specify an output file name, the multiplotter automatically generates one by appending the names of the input files. If you want to plot a large amount of files at the same time, the programme crashes because the file name is too long. The problem occurs from approx. 250 characters.

**Comment by tillbiskup** [comment]
This is again an upstream problem in ASpecD, or, to be more precise, a more general problem with the allowed length of filenames that most probably depends on both, operating and file system used.

A first fix is included in the current development version of the ASpecD framework:
https://github.com/tillbiskup/aspecd/commit/49f133d916d28d0929656bb140f0122dac0990be

The idea here is to simply replace the too long filename with its MD5 hash. While this is not particularly human-readable, it is unique. To make things more complicated, the actual saver has no information whatsoever how the proposed filename to save the figure to is composed, i.e. no chance to guess whether there is a suffix such as "Multiplotter". And there is no (simple) way to get the currently allowed length of a filename...

**Comment by tillbiskup** [comment]
The bug has been fixed (as described above, replacing the too long filename with its MD5 hash) in the latest release of ASpecD (0.8.2).
